esphome:
  name: vindriktning
  friendly_name: VINDRIKTNING
  platform: ESP8266
  board: d1_mini


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "WzRY730CQuuAFJ8tYYP1uIUXhIpV6rdXnSjiInWHz1U="

ota:
  password: ""


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 

captive_portal:

########## Setup #######################

i2c:
  sda: GPIO00
  scl: GPIO02
  scan: true

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13

uart:
  rx_pin: GPIO01
  baud_rate: 9600

  debug:
    direction: RX
    dummy_receiver: true
    after:
      delimiter: "\r\n"
    sequence:
      - lambda: |-
          UARTDebug::log_string(direction, bytes);  //Still log the data
          uint8_t checksum = 0;
          for (int i=0; i < bytes.size(); i++) {
            checksum+= bytes[i];
          }
          if (checksum==0){
            ESP_LOGD("UART","PM1006|PM1006k checksum validated, have %d", checksum);
            if (bytes.size()==20 and (bytes[0]==22 and bytes[1]==17 and bytes[2]==11)) {
              ESP_LOGD("UART", "Correct PM1006 response recieved. Updating sensors");
              id(pm2).publish_state(bytes[5]*256+bytes[6]); 
              id(pm1).publish_state(bytes[9]*256+bytes[10]);
              id(pm10).publish_state(bytes[13]*256+bytes[14]);
            }
            if (bytes.size()==16 and (bytes[0]==22 and bytes[1]==13 and bytes[2]==2)) {
              ESP_LOGD("UART", "Correct PM1006K response recieved. Updating sensors");
              id(pm2).publish_state(bytes[5]*256+bytes[6]); 
              id(pm1).publish_state(bytes[9]*256+bytes[10]);
              id(pm10).publish_state(bytes[13]*256+bytes[14]);
            }
          }
          else{
            ESP_LOGW("UART","PM1006|PM1006k checksum is wrong: %02x, expected zero. Sensors will not be updated", checksum);
          }
          
font:
  - file: "Roboto-Thin.ttf"
    id: font0
    size: 15
    glyphs: |-
      !"%()+=,-_.:°0123456789АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧЩЬЫЪЭЮЯABCDEFGHIJKLMNOPQRSTUVWXYZ абвгдеёжзийклмнопрстуфхцчщьыъэюяabcdefghijklmnopqrstuvwxyz'éèàòùç/&ôœìïöñ
    # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: font3
    size: 15 
  - file:
      type: gfonts
      family: Roboto
      weight: 700
    id: font2
    size: 30    
 
display:
  - platform: st7735
    model: "INITR_18BLACKTAB"
    reset_pin: GPIO05
    cs_pin: GPIO15
    dc_pin: GPIO04
    rotation: 0
    device_width: 128
    device_height: 160
    col_start: 0
    row_start: 0
    eight_bit_color: true
    update_interval: 5s
    id: my_display
    pages:
      - id: page1
        lambda: |-
          it.strftime(it.get_width() / 2, 8, id(font3), my_white, TextAlign::CENTER, "%H:%M", id(ntp).now());
          it.print(64, 22, id(font0), my_white, TextAlign::CENTER,  "PM1 мкг/m3");
          it.printf(64, 44, id(font2), my_white, TextAlign::CENTER, "%.0f", id(pm1).state);
          it.print(64, 70, id(font0), my_white, TextAlign::CENTER,  "PM2.5 мкг/m3");
          it.printf(64, 92, id(font2), my_yellow, TextAlign::CENTER, "%.0f ", id(pm2).state);
          it.print(64, 123, id(font0), my_white, TextAlign::CENTER,  "PM10 мкг/m3");
          it.printf(64, 145, id(font2), my_white, TextAlign::CENTER, "%.0f", id(pm10).state);
      - id: page2
        lambda: |-
          it.strftime(it.get_width() / 2, 8, id(font3), my_white, TextAlign::CENTER, "%H:%M", id(ntp).now());
          it.print(64, 22, id(font0), my_white, TextAlign::CENTER,  "НА УЛИЦЕ");
          it.printf(64, 44, id(font2), my_white, TextAlign::CENTER, "%.1f", id(temp_outdoor).state);
          it.print(64, 70, id(font0), my_white, TextAlign::CENTER,  "В ДОМЕ");
          it.printf(64, 92, id(font2), my_yellow, TextAlign::CENTER, "%.1f ", id(temp_hall).state);
          it.print(64, 123, id(font0), my_white, TextAlign::CENTER,  "СО2");
          it.printf(64, 145, id(font2), my_white, TextAlign::CENTER, "%.1f", id(co2).state);
interval:
  - interval: 5s
    then:
      - display.page.show_next: my_display
      - component.update: my_display        
   
color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%
  - id: my_black
    red: 0%
    green: 0%
    blue: 0%    

sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      id: bme280_temperature
    pressure:
      name: "BME280 Pressure"
      id: bme280_pressure
    humidity:
      name: "BME280 Realtive Humidity"
      id: bme280_humidity
    address: 0x76
    update_interval: 10s
  - platform: template
    name: "Altitude"
    lambda: |-
      const float STANDARD_SEA_LEVEL_PRESSURE = 1013.25; //in hPa, see note
      return ((id(bme280_temperature).state + 273.15) / 0.0065) * (powf((STANDARD_SEA_LEVEL_PRESSURE / id(bme280_pressure).state), 0.190234) - 1); // in meter
    update_interval: 60s
  - platform: template
    name: "Absolute Humidity"
    lambda: |-
      const float mw = 18.01534;    // molar mass of water g/mol
      const float r = 8.31447215;   // Universal gas constant J/mol/K
      return (6.112 * powf(2.718281828, (17.67 * id(bme280_temperature).state) / (id(bme280_temperature).state + 243.5)) * id(bme280_humidity).state * mw) / ((273.15 + id(bme280_temperature).state) * r); // in grams/m^3
    update_interval: 60s

  - platform: template
    name: "PM 1.0"
    id: "pm1"
    device_class: PM1
    accuracy_decimals: 0
    unit_of_measurement: µg/m³

  - platform: template
    name: "PM 2.5"
    id: "pm2"
    device_class: PM25
    accuracy_decimals: 0
    unit_of_measurement: µg/m³
  - platform: template
    name: "PM 10 "
    id: "pm10"
    device_class: PM10
    accuracy_decimals: 0
    unit_of_measurement: µg/m³
  - platform: homeassistant   # Температура на улице
    id: temp_outdoor
    entity_id: sensor.93_01_temp 
  - platform: homeassistant   # Температура в доме
    id: temp_hall
    entity_id: sensor.0xa4c1387ab81dc9bd_temperature
  - platform: homeassistant   # CO2
    id: co2
    entity_id: sensor.0x00124b001d3b8107_co2  


       
time:
  - platform: homeassistant
    id: ntp